### ISSUE TITLE
numpy error

### ISSUE THREAD

**Issue by hor1k1t4** [thomas-xin/Miza#24]
Unable to compare versions for numpy>=1.17: need=1.17 found=None. This is unusual. Consider reinstalling numpy.

Traceback (most recent call last):
  File "C:\Users\User\Downloads\MIZA\bot.py", line 4652, in __exit__
    raise exc_value
  File "commands/MAIN.py", line 1638, in _nocommand_
    m = await ask(message, guild, channel, user, argv, name="ask", flags=flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "commands/STRING.py", line 544, in __call__
    await fut
  File "C:\Users\User\Downloads\MIZA\common.py", line 2304, in sub_submit
    resp = await asyncio.wait_for(wrap_future(fut), timeout=3)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 479, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "C:\Users\User\Downloads\MIZA\common.py", line 2459, in on_done
    res = fut.result()
          ^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\User\Downloads\MIZA\common.py", line 2459, in on_done
    res = fut.result()
          ^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
ValueError: Unable to compare versions for numpy>=1.17: need=1.17 found=None. This is unusual. Consider reinstalling numpy.

But my numpy vers ==1.24.2...

**Comment by thomas-xin** [comment]
You've already attempted reinstalling I presume? Do you have multiple versions of Python installed and/or are using a virtual environment?

**Comment by hor1k1t4** [comment]
Yep, i try reinstall, but the error has not gone anywhere, there is only one python on the computer

**Comment by hor1k1t4** [comment]
Only a complete reinstallation of python on the computer helped
