### ISSUE TITLE
Slow ?

### ISSUE THREAD

**Issue by hor1k1t4** [thomas-xin/Miza#27]
Hello again 😬, i hope I 'm not boring you ), but a question, for what reasons can ai in a bot sometimes take a long time to answer or ignore the question altogether?

**Comment by thomas-xin** [comment]
The AI features are currently not explicitly supported for self-hosting. It is recommended to use the official/main bot for these, because I've not yet gotten around to making all of them work on other devices. I will try to fix bugs that are easy to, but I will not be directly adding support for platforms as of right now.

That said, to answer your question, APIs being used can time out due to high demand, locally hosted models can time out due to insufficient memory, there are a lot of variables involved here due to the nature of how the features are designed and integrated.

**Comment by hor1k1t4** [comment]
He just doesn't eat much RAM (less than 30% uses), the disk too, the processor is straight occasionally, but mostly feels perfect, and the response can sometimes take up to 5 minutes to come (and usually 30 - 60 seconds)

**Comment by thomas-xin** [comment]
Do you have an OpenAI account assigned, or are you using the bot for the free AIs? The free ones can take an especially long time

**Comment by hor1k1t4** [comment]
There is an account on openai, but without chatgpt plus (I haven't spent their 10 gift dollars yet)

**Comment by thomas-xin** [comment]
I'm referring to the ChatGPT API key. GPT-4 access is not necessary.

Assuming you have this set up; do you notice any errors when it takes multiple minutes?

**Comment by hor1k1t4** [comment]
That's the point, there are no errors, but sometimes it can take a long time to answer or not at all.
Yes, I use the openai api key

**Comment by hor1k1t4** [comment]
Could it be because of a free account on the openai api ?

**Comment by thomas-xin** [comment]
If it takes longer than about 30 seconds there should be a `concurrent.futures.TimeoutError` in the log, and a retry attempted. It is very strange that you're getting a higher delay.

**Comment by hor1k1t4** [comment]
I was just flipping through the logs, once she got out and just gave this:

Traceback (most recent call last):
  File "C:\Users\User\Desktop\Miza\misc\x-image.py", line 2985, in evaluate
    out = evalImg(*args)
          ^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\Miza\misc\x-image.py", line 2820, in evalImg
    new = eval(url)(*args)
          ^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\Miza\misc\x-image.py", line 2463, in CBAI
    return cb.ai(*prompt, refs=refs, im=im)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\Miza\misc\convobot.py", line 1508, in ai
    response, cost, uoai, expapi = self.gptcomplete(u, q, refs=refs)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\Miza\misc\convobot.py", line 786, in gptcomplete
    text = self.au(q3, stop=["1"], force=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\Miza\misc\convobot.py", line 1491, in au
    resp = funcs.pop(0)(prompt, stop=stop)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\Miza\misc\convobot.py", line 1344, in chatgpt
    res = fut.result(timeout=240)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 458, in result
    raise TimeoutError()
TimeoutError
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Miza\common.py", line 2176, in is_strict_running
    if proc.status() == "zombie":
       ^^^^^^^^^^^
AttributeError: 'Process' object has no attribute 'status'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\psutil\_pswindows.py", line 688, in wrapper
    return fun(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\psutil\_pswindows.py", line 942, in create_time
    user, system, created = cext.proc_times(self.pid)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^
ProcessLookupError: [Errno 3] assume no such process (originated from GetExitCodeProcess != STILL_ACTIVE)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\psutil\__init__.py", line 361, in _init
    self.create_time()
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\psutil\__init__.py", line 714, in create_time
    self._create_time = self._proc.create_time()
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\psutil\_pswindows.py", line 690, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.NoSuchProcess: process no longer exists (pid=2736)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\Desktop\Miza\common.py", line 2220, in proc_communicate
    if not is_strict_running(proc):
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\Miza\common.py", line 2183, in is_strict_running
    proc = psutil.Process(proc.pid)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\psutil\__init__.py", line 332, in __init__
    self._init(pid)
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\psutil\__init__.py", line 373, in _init
    raise NoSuchProcess(pid, msg='process PID not found')
psutil.NoSuchProcess: process PID not found (pid=2736)

**Comment by thomas-xin** [comment]
Interesting that you're running it on python 3.11; the last time I tried a while back it did not work. The main Miza runs on 3.10 at the moment.

I'm not sure if this is the problem though, there seems to be more underlying because it's calling the chatgpt command

I'll have a closer look later

**Comment by hor1k1t4** [comment]
Thank you, then I will wait and try to figure it out in parallel)

**Comment by hor1k1t4** [comment]
By the way, on more powerful hardware, the situation has become better, but sometimes he also thinks for 2-3 minutes, although at this moment the processor literally feels at 0%, and uses only 10 memory%

**Comment by thomas-xin** [comment]
Delays during requests are an issue I've currently been trying to debug actually, so I'm not 100% sure how to fix this yet.
