### ISSUE TITLE
name 'embedding' is not defined

### ISSUE THREAD

**Issue by hor1k1t4** [thomas-xin/Miza#29]
Error in title <3
After call `ask`

**Comment by thomas-xin** [comment]
I am assuming this is on the latest version? What python version are you running at the moment?

"embedding" I assume would be the function located in x-image.py, run under the 3rd compute subprocess and used for text embedding search; this may also currently have compatibility issues right now as I am in the process of working with different hardware setups. The name error you specified is not one I've experienced at all, and I would need a bit of time to investigate.

**Comment by hor1k1t4** [comment]
Python 3.11.3

Traceback:

['embedding', '$', ['中野二乃: @Miza_Test Hello cute']]
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Miza\misc\x-image.py", line 3048, in evaluate
    out = evalImg(*args)
          ^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\Miza\misc\x-image.py", line 2875, in evalImg
    new = eval(url)(*args)
          ^^^^^^^^^
  File "<string>", line 1, in <module>
NameError: name 'embedding' is not defined
<__main__.Bot.set_classes.<locals>.ExtendedMessage object at 0x0000024771197F20>
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Miza\bot.py", line 4652, in __exit__
    raise exc_value
  File "commands/MAIN.py", line 1638, in _nocommand_
    m = await ask(message, guild, channel, user, argv, name="ask", flags=flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "commands/STRING.py", line 546, in __call__
    await register_embedding(m.id, name, content)
  File "commands/STRING.py", line 368, in register_embedding
    data = await process_image("embedding", "$", ["\n".join(inp)], fix=3, timeout=60)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\Miza\common.py", line 2304, in sub_submit
    resp = await asyncio.wait_for(wrap_future(fut), timeout=3)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 479, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\Miza\common.py", line 2459, in on_done
    res = fut.result()
          ^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
NameError: name 'embedding' is not defined

**Comment by hor1k1t4** [comment]
Sry, its my error, i dont update common.py file 😬
